import "./globals.css";
import { Toaster } from "@/components/ui/toaster"


export const metadata = {
  title: "Fragments-ui",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="bg-[#0c0d2e]"
      >
        {children}
        <Toaster />

      </body>
    </html>
  );
}
